/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaip;

import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.naming.directory.InitialDirContext;
import javax.naming.NamingEnumeration;
import javax.naming.NamingException;
import javax.swing.DefaultListModel;

public class JavaDNS extends javax.swing.JFrame {

    private byte[] b;

    public JavaDNS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProses = new javax.swing.JButton();
        textDomain = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHasil = new javax.swing.JList<>();
        Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JONI PRIANTO - PEMROGRAMAN JARINGAN");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listHasil);

        Label.setText("Hasil DNS Lookup :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textDomain)
                                .addGap(18, 18, 18)
                                .addComponent(btnProses)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(textDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        InetAddress inetAddress;
        String domain = textDomain.getText();
        DefaultListModel mod = new DefaultListModel();
        listHasil.setModel(mod);
        try {
            if (Character.isDigit(domain.charAt(0))){
                
                byte[] b = new byte[4];
                String[]bytes = domain.split("[.]");
                for (int i = 0; i < bytes.length; i++){
                    b[i] = new Integer(bytes[i]).byteValue();
                } 
                  inetAddress = InetAddress.getByAddress(b);
            } else {
                inetAddress = InetAddress.getByName(domain);
            }
            
            String hostName = "Host : "+ inetAddress.getHostName();
            mod.addElement(hostName);
            String IPAddress = "IP : " + inetAddress.getHostAddress() + "\n";
            mod.addElement(IPAddress);
            
            InitialDirContext iDirc = new  InitialDirContext();
            
            javax.naming.directory.Attributes attributes = iDirc.getAttributes("dns:/" + inetAddress.getHostName());
            
            NamingEnumeration attributeEnumeration = attributes.getAll();
            mod.addElement("Informasi DNS");
            
            while (attributeEnumeration.hasMore()){
                mod.addElement(attributeEnumeration.next());
            }
            attributeEnumeration.close();
        } catch (UnknownHostException exception) {
            System.err.println("error: Domain tidak diketahui '" + domain + "'");
        } catch (NamingException exception) {
            System.err.println("error: Tidak ada Record DNS di Domain '" + domain + "'");
        }
        
        
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaDNS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton btnProses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listHasil;
    private javax.swing.JTextField textDomain;
    // End of variables declaration//GEN-END:variables
}
